import type { Metadata } from 'next'
import { CmsContent, ServerContext } from '@remkoj/optimizely-cms-react/rsc'
import { client } from '@/api'
import { factory } from '@/components/factory'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const ctx: ServerContext = new ServerContext({
    factory,
    client,
    mode: 'public'
  });
  return (
    <html lang="en">
      <body>
        <header style={{ borderBottom: "2px solid #000", minHeight: "25px", marginBottom: '5px' }}>
          {/*<CmsContent contentLink={{key: "7e9d73a0f7bd416aab12ef33d1d239c6"}} variant='header' ctx={ctx} />*/}
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
