import type { Metadata } from 'next'
import { CmsContent } from '@remkoj/optimizely-cms-react/rsc'
import { OptimizelyOneProvider, OptimizelyOneGadget, PageActivator } from '@remkoj/optimizely-one-nextjs/client'
import { publishedContext as ctx } from '@/api'
import Link from 'next/link'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <OptimizelyOneProvider>
          <PageActivator />
          <header style={{ borderBottom: '2px solid #000', minHeight: '25px', marginBottom: '5px' }}>
            <Link href='/'>
              <CmsContent contentLink={{key: '7950541bb6a84d049784cb6f46262c12'}} variant='header' ctx={ctx} />
            </Link>
          </header>
          {children}
          <OptimizelyOneGadget />
        </OptimizelyOneProvider>
      </body>
    </html>
  )
}
