enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

packageExtensions:
  "@inquirer/core@^10.0.1":
    dependencies:
      "@types/node": "*"

pnpMode: strict
