enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.yarn?
  - .env.yarn.local?

packageExtensions:
  '@inquirer/core@^10.0.1':
    dependencies:
      '@types/node': '*'
  '@hey-api/openapi-ts@*':
    dependencies:
      '@hey-api/client-fetch': '*'

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.9.1.cjs
