enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

packageExtensions:
  openapi-typescript-codegen@*:
    dependencies:
      "@types/json-schema": "*"

pnpMode: strict
