enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

packageExtensions:
  "@optimizely/react-sdk@^3.4.0":
    dependencies:
      "@babel/runtime": "*"
  openapi-typescript-codegen@0.30.0:
    dependencies:
      "@types/json-schema": "*"

pnpMode: strict
