enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.yarn?
  - .env.yarn.local?

packageExtensions:
  "@inquirer/core@^10.0.1":
    dependencies:
      "@types/node": "*"
  "@hey-api/openapi-ts@^0.64":
    dependencies:
      "@hey-api/client-fetch": "^0.8"

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.7.0.cjs
