enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  #- .env?
  #- .env.local?
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

packageExtensions:
  "@hey-api/openapi-ts@*":
    dependencies:
      "@hey-api/client-fetch": "*"
  "@inquirer/core@^10.0.1":
    dependencies:
      "@types/node": "*"

pnpMode: strict
