enableGlobalCache: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

pnpMode: strict

packageExtensions:
  "openapi-typescript-codegen@0.30.0":
    dependencies:
      "@types/json-schema": "*"
