// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ContentTypesListData, ContentTypesListResponses, ContentTypesListErrors, ContentTypesCreateData, ContentTypesCreateResponses, ContentTypesCreateErrors, ContentTypesDeleteData, ContentTypesDeleteResponses, ContentTypesDeleteErrors, ContentTypesGetData, ContentTypesGetResponses, ContentTypesGetErrors, ContentTypesPatchData, ContentTypesPatchResponses, ContentTypesPatchErrors, DisplayTemplatesListData, DisplayTemplatesListResponses, DisplayTemplatesListErrors, DisplayTemplatesCreateData, DisplayTemplatesCreateResponses, DisplayTemplatesCreateErrors, DisplayTemplatesDeleteData, DisplayTemplatesDeleteResponses, DisplayTemplatesDeleteErrors, DisplayTemplatesGetData, DisplayTemplatesGetResponses, DisplayTemplatesGetErrors, DisplayTemplatesPatchData, DisplayTemplatesPatchResponses, DisplayTemplatesPatchErrors, PropertyFormatsListData, PropertyFormatsListResponses, PropertyFormatsListErrors, PropertyFormatsGetData, PropertyFormatsGetResponses, PropertyFormatsGetErrors, PropertyGroupsListData, PropertyGroupsListResponses, PropertyGroupsListErrors, PropertyGroupsCreateData, PropertyGroupsCreateResponses, PropertyGroupsCreateErrors, PropertyGroupsDeleteData, PropertyGroupsDeleteResponses, PropertyGroupsDeleteErrors, PropertyGroupsGetData, PropertyGroupsGetResponses, PropertyGroupsGetErrors, PropertyGroupsPatchData, PropertyGroupsPatchResponses, PropertyGroupsPatchErrors } from './types.gen';
import { contentTypesListResponseTransformer, contentTypesCreateResponseTransformer, contentTypesDeleteResponseTransformer, contentTypesGetResponseTransformer, contentTypesPatchResponseTransformer, displayTemplatesListResponseTransformer, displayTemplatesCreateResponseTransformer, displayTemplatesDeleteResponseTransformer, displayTemplatesGetResponseTransformer, displayTemplatesPatchResponseTransformer, propertyFormatsListResponseTransformer, propertyFormatsGetResponseTransformer, propertyGroupsListResponseTransformer, propertyGroupsCreateResponseTransformer, propertyGroupsDeleteResponseTransformer, propertyGroupsGetResponseTransformer, propertyGroupsPatchResponseTransformer } from './transformers.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List content types
 * List content types using the provided parameters.
 */
export const contentTypesList = <ThrowOnError extends boolean = false>(options?: Options<ContentTypesListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ContentTypesListResponses, ContentTypesListErrors, ThrowOnError>({
        responseTransformer: contentTypesListResponseTransformer,
        url: '/contenttypes',
        ...options
    });
};

/**
 * Create content type
 * Create a new content type.
 */
export const contentTypesCreate = <ThrowOnError extends boolean = false>(options: Options<ContentTypesCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ContentTypesCreateResponses, ContentTypesCreateErrors, ThrowOnError>({
        responseTransformer: contentTypesCreateResponseTransformer,
        url: '/contenttypes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete content type
 * Deletes the content type with the provided key. If a content type with the provided key does not exist an error is returned.
 */
export const contentTypesDelete = <ThrowOnError extends boolean = false>(options: Options<ContentTypesDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<ContentTypesDeleteResponses, ContentTypesDeleteErrors, ThrowOnError>({
        responseTransformer: contentTypesDeleteResponseTransformer,
        url: '/contenttypes/{key}',
        ...options
    });
};

/**
 * Get content type
 * Get the content type with the provided key.
 */
export const contentTypesGet = <ThrowOnError extends boolean = false>(options: Options<ContentTypesGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ContentTypesGetResponses, ContentTypesGetErrors, ThrowOnError>({
        responseTransformer: contentTypesGetResponseTransformer,
        url: '/contenttypes/{key}',
        ...options
    });
};

/**
 * Patch content type
 * Patch an existing content type. If a content type with the provided key does not exist an error is returned.
 */
export const contentTypesPatch = <ThrowOnError extends boolean = false>(options: Options<ContentTypesPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<ContentTypesPatchResponses, ContentTypesPatchErrors, ThrowOnError>({
        responseTransformer: contentTypesPatchResponseTransformer,
        url: '/contenttypes/{key}',
        ...options,
        headers: {
            'Content-Type': 'application/merge-patch+json',
            ...options.headers
        }
    });
};

/**
 * List display templates
 * List display templates using the provided parameters.
 */
export const displayTemplatesList = <ThrowOnError extends boolean = false>(options?: Options<DisplayTemplatesListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<DisplayTemplatesListResponses, DisplayTemplatesListErrors, ThrowOnError>({
        responseTransformer: displayTemplatesListResponseTransformer,
        url: '/displaytemplates',
        ...options
    });
};

/**
 * Create display template
 * Create a new display template.
 */
export const displayTemplatesCreate = <ThrowOnError extends boolean = false>(options: Options<DisplayTemplatesCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<DisplayTemplatesCreateResponses, DisplayTemplatesCreateErrors, ThrowOnError>({
        responseTransformer: displayTemplatesCreateResponseTransformer,
        url: '/displaytemplates',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete display template
 * Deletes the display template with the provided key.
 */
export const displayTemplatesDelete = <ThrowOnError extends boolean = false>(options: Options<DisplayTemplatesDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DisplayTemplatesDeleteResponses, DisplayTemplatesDeleteErrors, ThrowOnError>({
        responseTransformer: displayTemplatesDeleteResponseTransformer,
        url: '/displaytemplates/{key}',
        ...options
    });
};

/**
 * Get display template
 * Get the display template with the provided key.
 */
export const displayTemplatesGet = <ThrowOnError extends boolean = false>(options: Options<DisplayTemplatesGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<DisplayTemplatesGetResponses, DisplayTemplatesGetErrors, ThrowOnError>({
        responseTransformer: displayTemplatesGetResponseTransformer,
        url: '/displaytemplates/{key}',
        ...options
    });
};

/**
 * Patch display template
 * Patch an existing display template.
 */
export const displayTemplatesPatch = <ThrowOnError extends boolean = false>(options: Options<DisplayTemplatesPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<DisplayTemplatesPatchResponses, DisplayTemplatesPatchErrors, ThrowOnError>({
        responseTransformer: displayTemplatesPatchResponseTransformer,
        url: '/displaytemplates/{key}',
        ...options,
        headers: {
            'Content-Type': 'application/merge-patch+json',
            ...options.headers
        }
    });
};

/**
 * List property formats
 * List all property formats using the provided options.
 */
export const propertyFormatsList = <ThrowOnError extends boolean = false>(options?: Options<PropertyFormatsListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<PropertyFormatsListResponses, PropertyFormatsListErrors, ThrowOnError>({
        responseTransformer: propertyFormatsListResponseTransformer,
        url: '/propertyformats',
        ...options
    });
};

/**
 * Get property format
 * Get the property format with the provided key.
 */
export const propertyFormatsGet = <ThrowOnError extends boolean = false>(options: Options<PropertyFormatsGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<PropertyFormatsGetResponses, PropertyFormatsGetErrors, ThrowOnError>({
        responseTransformer: propertyFormatsGetResponseTransformer,
        url: '/propertyformats/{key}',
        ...options
    });
};

/**
 * List property groups
 * List property groups using the provided options.
 */
export const propertyGroupsList = <ThrowOnError extends boolean = false>(options?: Options<PropertyGroupsListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<PropertyGroupsListResponses, PropertyGroupsListErrors, ThrowOnError>({
        responseTransformer: propertyGroupsListResponseTransformer,
        url: '/propertygroups',
        ...options
    });
};

/**
 * Create property group
 * Create a new property group.
 */
export const propertyGroupsCreate = <ThrowOnError extends boolean = false>(options: Options<PropertyGroupsCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PropertyGroupsCreateResponses, PropertyGroupsCreateErrors, ThrowOnError>({
        responseTransformer: propertyGroupsCreateResponseTransformer,
        url: '/propertygroups',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete property group
 * Deletes the property group with the provided key.
 */
export const propertyGroupsDelete = <ThrowOnError extends boolean = false>(options: Options<PropertyGroupsDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<PropertyGroupsDeleteResponses, PropertyGroupsDeleteErrors, ThrowOnError>({
        responseTransformer: propertyGroupsDeleteResponseTransformer,
        url: '/propertygroups/{key}',
        ...options
    });
};

/**
 * Get property group
 * Get the property group with the provided key.
 */
export const propertyGroupsGet = <ThrowOnError extends boolean = false>(options: Options<PropertyGroupsGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<PropertyGroupsGetResponses, PropertyGroupsGetErrors, ThrowOnError>({
        responseTransformer: propertyGroupsGetResponseTransformer,
        url: '/propertygroups/{key}',
        ...options
    });
};

/**
 * Patch property group
 * Patch an existing property group.
 */
export const propertyGroupsPatch = <ThrowOnError extends boolean = false>(options: Options<PropertyGroupsPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<PropertyGroupsPatchResponses, PropertyGroupsPatchErrors, ThrowOnError>({
        responseTransformer: propertyGroupsPatchResponseTransformer,
        url: '/propertygroups/{key}',
        ...options,
        headers: {
            'Content-Type': 'application/merge-patch+json',
            ...options.headers
        }
    });
};