// This file is auto-generated by @hey-api/openapi-ts

import type { ContentTypesCreateResponse, ContentTypesDeleteResponse, ContentTypesGetResponse, ContentTypesListResponse, ContentTypesPatchResponse, DisplayTemplatesCreateResponse, DisplayTemplatesDeleteResponse, DisplayTemplatesGetResponse, DisplayTemplatesListResponse, DisplayTemplatesPatchResponse, PropertyFormatsGetResponse, PropertyFormatsListResponse, PropertyGroupsCreateResponse, PropertyGroupsDeleteResponse, PropertyGroupsGetResponse, PropertyGroupsListResponse, PropertyGroupsPatchResponse } from './types.gen';

const contentTypePageSchemaResponseTransformer = (data: any) => {
    if (data.items) {
        data.items = data.items.map((item: any) => {
            return contentTypeSchemaResponseTransformer(item);
        });
    }
    return data;
};

const contentTypeSchemaResponseTransformer = (data: any) => {
    if (data.created) {
        data.created = new Date(data.created);
    }
    if (data.lastModified) {
        data.lastModified = new Date(data.lastModified);
    }
    return data;
};

export const contentTypesListResponseTransformer = async (data: any): Promise<ContentTypesListResponse> => {
    data = contentTypePageSchemaResponseTransformer(data);
    return data;
};

export const contentTypesCreateResponseTransformer = async (data: any): Promise<ContentTypesCreateResponse> => {
    data = contentTypeSchemaResponseTransformer(data);
    return data;
};

export const contentTypesDeleteResponseTransformer = async (data: any): Promise<ContentTypesDeleteResponse> => {
    data = contentTypeSchemaResponseTransformer(data);
    return data;
};

export const contentTypesGetResponseTransformer = async (data: any): Promise<ContentTypesGetResponse> => {
    data = contentTypeSchemaResponseTransformer(data);
    return data;
};

export const contentTypesPatchResponseTransformer = async (data: any): Promise<ContentTypesPatchResponse> => {
    data = contentTypeSchemaResponseTransformer(data);
    return data;
};

const displayTemplatePageSchemaResponseTransformer = (data: any) => {
    if (data.items) {
        data.items = data.items.map((item: any) => {
            return displayTemplateSchemaResponseTransformer(item);
        });
    }
    return data;
};

const displayTemplateSchemaResponseTransformer = (data: any) => {
    if (data.created) {
        data.created = new Date(data.created);
    }
    if (data.lastModified) {
        data.lastModified = new Date(data.lastModified);
    }
    return data;
};

export const displayTemplatesListResponseTransformer = async (data: any): Promise<DisplayTemplatesListResponse> => {
    data = displayTemplatePageSchemaResponseTransformer(data);
    return data;
};

export const displayTemplatesCreateResponseTransformer = async (data: any): Promise<DisplayTemplatesCreateResponse> => {
    data = displayTemplateSchemaResponseTransformer(data);
    return data;
};

export const displayTemplatesDeleteResponseTransformer = async (data: any): Promise<DisplayTemplatesDeleteResponse> => {
    data = displayTemplateSchemaResponseTransformer(data);
    return data;
};

export const displayTemplatesGetResponseTransformer = async (data: any): Promise<DisplayTemplatesGetResponse> => {
    data = displayTemplateSchemaResponseTransformer(data);
    return data;
};

export const displayTemplatesPatchResponseTransformer = async (data: any): Promise<DisplayTemplatesPatchResponse> => {
    data = displayTemplateSchemaResponseTransformer(data);
    return data;
};

const propertyFormatPageSchemaResponseTransformer = (data: any) => {
    if (data.items) {
        data.items = data.items.map((item: any) => {
            return propertyFormatSchemaResponseTransformer(item);
        });
    }
    return data;
};

const propertyFormatSchemaResponseTransformer = (data: any) => {
    if (data.created) {
        data.created = new Date(data.created);
    }
    if (data.lastModified) {
        data.lastModified = new Date(data.lastModified);
    }
    return data;
};

export const propertyFormatsListResponseTransformer = async (data: any): Promise<PropertyFormatsListResponse> => {
    data = propertyFormatPageSchemaResponseTransformer(data);
    return data;
};

export const propertyFormatsGetResponseTransformer = async (data: any): Promise<PropertyFormatsGetResponse> => {
    data = propertyFormatSchemaResponseTransformer(data);
    return data;
};

const propertyGroupPageSchemaResponseTransformer = (data: any) => {
    if (data.items) {
        data.items = data.items.map((item: any) => {
            return propertyGroupSchemaResponseTransformer(item);
        });
    }
    return data;
};

const propertyGroupSchemaResponseTransformer = (data: any) => {
    if (data.created) {
        data.created = new Date(data.created);
    }
    if (data.lastModified) {
        data.lastModified = new Date(data.lastModified);
    }
    return data;
};

export const propertyGroupsListResponseTransformer = async (data: any): Promise<PropertyGroupsListResponse> => {
    data = propertyGroupPageSchemaResponseTransformer(data);
    return data;
};

export const propertyGroupsCreateResponseTransformer = async (data: any): Promise<PropertyGroupsCreateResponse> => {
    data = propertyGroupSchemaResponseTransformer(data);
    return data;
};

export const propertyGroupsDeleteResponseTransformer = async (data: any): Promise<PropertyGroupsDeleteResponse> => {
    data = propertyGroupSchemaResponseTransformer(data);
    return data;
};

export const propertyGroupsGetResponseTransformer = async (data: any): Promise<PropertyGroupsGetResponse> => {
    data = propertyGroupSchemaResponseTransformer(data);
    return data;
};

export const propertyGroupsPatchResponseTransformer = async (data: any): Promise<PropertyGroupsPatchResponse> => {
    data = propertyGroupSchemaResponseTransformer(data);
    return data;
};
