import type { CliModule } from '../types.js'
import chalk from 'chalk'
import figures from 'figures'
import fs from 'node:fs/promises'
import path from 'node:path'

const SECTION_START = '<!-- @remkoj/optimizely-packages:start -->'
const SECTION_END = '<!-- @remkoj/optimizely-packages:end -->'

type ProjectAiModule = CliModule<{
  force?: boolean
  tools?: string[]
}>

export const ProjectAiCommand: ProjectAiModule = {
  command: 'project:ai',
  describe: 'Create or update AI assistant configuration files (AGENTS.md, CLAUDE.md, GitHub Copilot, Cursor) so installed @remkoj package documentation is available to the model',
  builder: (yargs) => {
    yargs.option('force', {
      alias: 'f',
      description: 'Overwrite existing files entirely instead of merging into existing content',
      boolean: true,
      type: 'boolean',
      demandOption: false,
      default: false,
    })
    yargs.option('tools', {
      alias: 't',
      description: 'AI tools to configure',
      array: true,
      type: 'string',
      choices: ['agents', 'claude', 'copilot', 'cursor'],
      demandOption: false,
      default: ['agents', 'claude', 'copilot', 'cursor'],
    })
    return yargs
  },
  handler: async (args) => {
    const projectPath = path.isAbsolute(args.path)
      ? args.path
      : path.normalize(path.join(process.cwd(), args.path))
    const force: boolean = args.force ?? false
    const tools: string[] = args.tools ?? ['agents', 'claude', 'copilot', 'cursor']

    // Discover installed @remkoj packages that include AGENTS.md
    process.stdout.write(`\n${figures.arrowRight} Scanning for @remkoj packages with AGENTS.md\n`)
    const packages = await findRemkojPackages(projectPath)

    if (packages.length === 0) {
      process.stderr.write(
        chalk.yellowBright(`\n${figures.warning} No @remkoj packages with AGENTS.md found in node_modules — run \`npm install\` first.\n`),
      )
      return
    }

    for (const pkg of packages) {
      process.stdout.write(`  ${chalk.greenBright(figures.tick)} ${chalk.bold(pkg.name)}\n`)
    }

    if (tools.includes('agents')) {
      process.stdout.write(`\n${figures.arrowRight} Updating AGENTS.md\n`)
      await updateWithSectionMarkers(
        path.join(projectPath, 'AGENTS.md'),
        buildAgentsMdSection(packages, projectPath),
        buildAgentsMdPreamble(),
        force,
        projectPath,
      )
    }

    if (tools.includes('claude')) {
      process.stdout.write(`\n${figures.arrowRight} Writing CLAUDE.md\n`)
      await writeNewFileOnly(
        path.join(projectPath, 'CLAUDE.md'),
        `# CLAUDE.md\n\nSee [AGENTS.md](./AGENTS.md) for guidance on working with the Optimizely DXP packages in this project.\n`,
        force,
        projectPath,
      )
    }

    if (tools.includes('copilot')) {
      process.stdout.write(`\n${figures.arrowRight} Writing GitHub Copilot instructions\n`)
      await updateCopilotInstructions(projectPath, force)
    }

    if (tools.includes('cursor')) {
      process.stdout.write(`\n${figures.arrowRight} Writing Cursor rules\n`)
      const rulesDir = path.join(projectPath, '.cursor', 'rules')
      await ensureDir(rulesDir)
      await writeCursorRules(path.join(rulesDir, 'optimizely-packages.mdc'), packages, projectPath)
    }

    process.stdout.write(
      `\n${chalk.greenBright(chalk.bold(figures.tick))} AI assistant configuration updated successfully\n`,
    )
  },
}

export default ProjectAiCommand

// ── Helpers ───────────────────────────────────────────────────────────────────

async function findRemkojPackages(
  projectPath: string,
): Promise<Array<{ name: string; agentsPath: string }>> {
  const scopeDir = path.join(projectPath, 'node_modules', '@remkoj')
  const packages: Array<{ name: string; agentsPath: string }> = []
  try {
    const dirs = await fs.readdir(scopeDir)
    for (const dir of dirs) {
      const agentsPath = path.join(scopeDir, dir, 'AGENTS.md')
      try {
        await fs.access(agentsPath)
        packages.push({ name: `@remkoj/${dir}`, agentsPath })
      } catch {
        // Package has no AGENTS.md — skip silently
      }
    }
  } catch {
    // @remkoj scope directory not found in node_modules
  }
  return packages
}

function wrapSection(content: string): string {
  return `${SECTION_START}\n${content}\n${SECTION_END}`
}

function buildReferenceList(
  packages: Array<{ name: string; agentsPath: string }>,
  projectPath: string,
): string {
  return packages
    .map((pkg) => {
      const rel = path.relative(projectPath, pkg.agentsPath).replace(/\\/g, '/')
      return `- [\`${pkg.name}\`](${rel})`
    })
    .join('\n')
}

function buildAgentsMdPreamble(): string {
  return `# AI Agent Documentation — Optimizely DXP Packages

The section below is auto-generated by \`opti-cms project:ai\`. Re-run after installing or upgrading \`@remkoj\` packages.

`
}

function buildAgentsMdSection(
  packages: Array<{ name: string; agentsPath: string }>,
  projectPath: string,
): string {
  return `The following \`@remkoj\` packages are installed. Read their \`AGENTS.md\` for documentation:\n\n${buildReferenceList(packages, projectPath)}`
}

/**
 * Creates or updates the auto-generated section delimited by SECTION_START/SECTION_END markers.
 *
 * - File absent: creates it with preamble + section.
 * - File present with markers: replaces the section in-place.
 * - File present without markers: appends the section (preserves existing content).
 * - force=true: always replaces the entire file with preamble + section.
 */
async function updateWithSectionMarkers(
  filePath: string,
  sectionContent: string,
  preamble: string,
  force: boolean,
  projectPath: string,
): Promise<void> {
  const rel = path.relative(projectPath, filePath)
  const section = wrapSection(sectionContent)

  let existing: string | undefined
  try {
    existing = await fs.readFile(filePath, 'utf-8')
  } catch {
    // File does not exist — will be created
  }

  if (!existing || force) {
    await fs.writeFile(filePath, preamble + section + '\n', 'utf-8')
    process.stdout.write(
      `  ${chalk.greenBright(figures.tick)} ${existing ? 'Replaced' : 'Created'} ${rel}\n`,
    )
    return
  }

  if (existing.includes(SECTION_START) && existing.includes(SECTION_END)) {
    const before = existing.slice(0, existing.indexOf(SECTION_START))
    const after = existing.slice(existing.indexOf(SECTION_END) + SECTION_END.length)
    await fs.writeFile(filePath, before + section + after, 'utf-8')
    process.stdout.write(`  ${chalk.greenBright(figures.tick)} Updated section in ${rel}\n`)
  } else {
    await fs.writeFile(filePath, existing.trimEnd() + '\n\n' + section + '\n', 'utf-8')
    process.stdout.write(`  ${chalk.greenBright(figures.tick)} Appended section to ${rel}\n`)
  }
}

/**
 * Writes a file only when it does not already exist.
 * When force=true the file is always (re)written.
 */
async function writeNewFileOnly(
  filePath: string,
  content: string,
  force: boolean,
  projectPath: string,
): Promise<void> {
  const rel = path.relative(projectPath, filePath)
  let exists = false
  try {
    await fs.access(filePath)
    exists = true
  } catch {
    // File does not exist
  }

  if (exists && !force) {
    process.stdout.write(
      `  ${chalk.yellowBright(figures.info)} ${rel} already exists — use --force to overwrite\n`,
    )
    return
  }

  await fs.writeFile(filePath, content, 'utf-8')
  process.stdout.write(
    `  ${chalk.greenBright(figures.tick)} ${exists ? 'Replaced' : 'Created'} ${rel}\n`,
  )
}

/**
 * Writes `.github/copilot-instructions.md`, referencing the project's
 * `AGENTS.md` — GitHub Copilot loads this file automatically, so the
 * per-package details already merged into `AGENTS.md` reach the model
 * without a separate instruction file per package.
 *
 * Also removes the per-package `remkoj-*.instructions.md` files left behind
 * by older versions of this command in `.github/instructions` and the legacy
 * `.vscode/instructions` location, and the deprecated
 * `github.copilot.chat.codeGeneration.instructions` key from
 * `.vscode/settings.json` if it was written by a previous run.
 */
async function updateCopilotInstructions(projectPath: string, force: boolean): Promise<void> {
  const githubDir = path.join(projectPath, '.github')
  await ensureDir(githubDir)

  await writeNewFileOnly(
    path.join(githubDir, 'copilot-instructions.md'),
    `# GitHub Copilot Instructions\n\nSee [AGENTS.md](../AGENTS.md) for guidance on working with the Optimizely DXP packages in this project.\n`,
    force,
    projectPath,
  )

  // Remove stale per-package instruction files from previous versions of this command
  const FILE_PREFIX = 'remkoj-'
  for (const dir of [path.join(githubDir, 'instructions'), path.join(projectPath, '.vscode', 'instructions')]) {
    try {
      const existing = await fs.readdir(dir)
      for (const f of existing) {
        if (f.startsWith(FILE_PREFIX) && f.endsWith('.instructions.md')) {
          await fs.unlink(path.join(dir, f))
        }
      }
    } catch {
      // Directory unreadable — ignore
    }
  }

  // Clean up the deprecated settings key written by previous versions of this command
  await removeDeprecatedCopilotSetting(projectPath)
}

async function removeDeprecatedCopilotSetting(projectPath: string): Promise<void> {
  const settingsFile = path.join(projectPath, '.vscode', 'settings.json')
  let settings: Record<string, unknown>
  try {
    settings = JSON.parse(await fs.readFile(settingsFile, 'utf-8')) as Record<string, unknown>
  } catch {
    return // File absent or invalid — nothing to clean up
  }

  const key = 'github.copilot.chat.codeGeneration.instructions'
  if (!(key in settings)) return

  type InstructionEntry = { file?: string; text?: string }
  const remaining = (settings[key] as InstructionEntry[]).filter(
    (e) => !e.file?.startsWith('node_modules/@remkoj/'),
  )

  if (remaining.length === 0) {
    delete settings[key]
  } else {
    settings[key] = remaining
  }

  await fs.writeFile(settingsFile, JSON.stringify(settings, null, 2) + '\n', 'utf-8')
  process.stdout.write(
    `  ${chalk.greenBright(figures.tick)} Removed deprecated setting from ${path.relative(projectPath, settingsFile)}\n`,
  )
}

/** Writes the Cursor rules file with a reference list; always regenerated since it is fully derived from node_modules. */
async function writeCursorRules(
  filePath: string,
  packages: Array<{ name: string; agentsPath: string }>,
  projectPath: string,
): Promise<void> {
  const rel = path.relative(projectPath, filePath)
  let exists = false
  try {
    await fs.access(filePath)
    exists = true
  } catch {
    // File does not exist
  }

  const list = buildReferenceList(packages, projectPath)
  const content = [
    '---',
    'description: Documentation for @remkoj Optimizely DXP packages installed in this project',
    'alwaysApply: true',
    '---',
    '',
    wrapSection(
      `The following \`@remkoj\` packages are installed. Read their \`AGENTS.md\` for documentation:\n\n${list}`,
    ),
    '',
  ].join('\n')

  await fs.writeFile(filePath, content, 'utf-8')
  process.stdout.write(
    `  ${chalk.greenBright(figures.tick)} ${exists ? 'Updated' : 'Created'} ${rel}\n`,
  )
}

async function ensureDir(dirPath: string): Promise<void> {
  await fs.mkdir(dirPath, { recursive: true })
}
